workflows:
  android-release:
    name: Android Release
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: |
          cd $CM_BUILD_DIR
          flutter pub get
      - name: Build APK
        script: |
          cd $CM_BUILD_DIR
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    instance_type: linux_x2
