// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqshoZpVv4Kn0YDPXDcwmYn-1UTBjqvc0',
    appId: '1:417435109092:web:6df67bb1fdb5533ebf8ef1',
    messagingSenderId: '417435109092',
    projectId: 'stockmaster-b3df1',
    authDomain: 'stockmaster-b3df1.firebaseapp.com',
    storageBucket: 'stockmaster-b3df1.firebasestorage.app',
    measurementId: 'G-KRGH8EFKJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAusLwWr8PeLmLFK9_CeLDxliAagN_bS6Q',
    appId: '1:417435109092:android:9daa8559e7e89f9ebf8ef1',
    messagingSenderId: '417435109092',
    projectId: 'stockmaster-b3df1',
    storageBucket: 'stockmaster-b3df1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAl1hcVi39S3JMGuB3valtoEDa7fo3Au4',
    appId: '1:417435109092:ios:1ac17cb123c0ea0ebf8ef1',
    messagingSenderId: '417435109092',
    projectId: 'stockmaster-b3df1',
    storageBucket: 'stockmaster-b3df1.firebasestorage.app',
    iosBundleId: 'com.example.stockmaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAl1hcVi39S3JMGuB3valtoEDa7fo3Au4',
    appId: '1:417435109092:ios:1ac17cb123c0ea0ebf8ef1',
    messagingSenderId: '417435109092',
    projectId: 'stockmaster-b3df1',
    storageBucket: 'stockmaster-b3df1.firebasestorage.app',
    iosBundleId: 'com.example.stockmaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqshoZpVv4Kn0YDPXDcwmYn-1UTBjqvc0',
    appId: '1:417435109092:web:9974df550acf1748bf8ef1',
    messagingSenderId: '417435109092',
    projectId: 'stockmaster-b3df1',
    authDomain: 'stockmaster-b3df1.firebaseapp.com',
    storageBucket: 'stockmaster-b3df1.firebasestorage.app',
    measurementId: 'G-1K484JT5B0',
  );
}
